src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\UserType;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'validators.user.email_already_exists')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank(message: 'validators.user.email_required')]
    #[Assert\Email(message: 'validators.user.email_invalid')]
    private ?string $email = null;

    /** @var list<string> The user roles */
    #[ORM\Column]
    private array $roles = [];

    /** @var string The hashed password */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 20, nullable: true, enumType: UserType::class)]
    private ?UserType $type = null;

    #[ORM\Column(length: 13, nullable: true)]
    private ?string $cnp = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $cui = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $companyName = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $barNumber = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $streetNumber = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $block = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $staircase = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $apartment = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $county = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $postalCode = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deletedAt = null;

    /** @var Collection<int, LegalCase> */
    #[ORM\OneToMany(targetEntity: LegalCase::class, mappedBy: 'user')]
    private Collection $legalCases;

    /** @var Collection<int, Notification> */
    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'user')]
    private Collection $notifications;

    public function __construct()
    {
        $this->legalCases = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /** @param list<string> $roles */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getType(): ?UserType
    {
        return $this->type;
    }

    public function setType(?UserType $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCnp(): ?string
    {
        return $this->cnp;
    }

    public function setCnp(?string $cnp): static
    {
        $this->cnp = $cnp;

        return $this;
    }

    public function getCui(): ?string
    {
        return $this->cui;
    }

    public function setCui(?string $cui): static
    {
        $this->cui = $cui;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    public function setCompanyName(?string $companyName): static
    {
        $this->companyName = $companyName;

        return $this;
    }

    public function getBarNumber(): ?string
    {
        return $this->barNumber;
    }

    public function setBarNumber(?string $barNumber): static
    {
        $this->barNumber = $barNumber;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getStreetNumber(): ?string
    {
        return $this->streetNumber;
    }

    public function setStreetNumber(?string $streetNumber): static
    {
        $this->streetNumber = $streetNumber;

        return $this;
    }

    public function getBlock(): ?string
    {
        return $this->block;
    }

    public function setBlock(?string $block): static
    {
        $this->block = $block;

        return $this;
    }

    public function getStaircase(): ?string
    {
        return $this->staircase;
    }

    public function setStaircase(?string $staircase): static
    {
        $this->staircase = $staircase;

        return $this;
    }

    public function getApartment(): ?string
    {
        return $this->apartment;
    }

    public function setApartment(?string $apartment): static
    {
        $this->apartment = $apartment;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCounty(): ?string
    {
        return $this->county;
    }

    public function setCounty(?string $county): static
    {
        $this->county = $county;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): static
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeImmutable $deletedAt): static
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function isDeleted(): bool
    {
        return $this->deletedAt !== null;
    }

    public function getFullName(): ?string
    {
        $parts = array_filter([$this->firstName, $this->lastName]);

        return $parts ? implode(' ', $parts) : null;
    }

    /** @return Collection<int, LegalCase> */
    public function getLegalCases(): Collection
    {
        return $this->legalCases;
    }

    /** @return Collection<int, Notification> */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function __toString(): string
    {
        return $this->getFullName() ?: $this->email;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\ChangePasswordType;
use App\Form\ProfileEditType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/profile')]
class ProfileController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $em,
        private TranslatorInterface $translator,
    ) {}

    #[Route('', name: 'app_profile', methods: ['GET'])]
    public function show(): Response
    {
        return $this->render('profile/show.html.twig', [
            'user' => $this->getUser(),
        ]);
    }

    #[Route('/edit', name: 'app_profile_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $form = $this->createForm(ProfileEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            $this->addFlash('success', $this->translator->trans('profile.flash.edit_success'));

            return $this->redirectToRoute('app_profile');
        }

        return $this->render('profile/edit.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/change-password', name: 'app_profile_change_password', methods: ['GET', 'POST'])]
    public function changePassword(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $form = $this->createForm(ChangePasswordType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $currentPassword = $form->get('currentPassword')->getData();

            if (!$passwordHasher->isPasswordValid($user, $currentPassword)) {
                $this->addFlash('danger', $this->translator->trans('profile.flash.current_password_wrong'));

                return $this->redirectToRoute('app_profile_change_password');
            }

            $newPassword = $form->get('newPassword')->getData();
            $user->setPassword($passwordHasher->hashPassword($user, $newPassword));
            $this->em->flush();

            $this->addFlash('success', $this->translator->trans('profile.flash.password_changed'));

            return $this->redirectToRoute('app_profile');
        }

        return $this->render('profile/change_password.html.twig', [
            'form' => $form,
        ]);
    }
}

templates/profile/change_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'profile.change_password.title'|trans }}{% endblock %}

{% block body %}
    <div class="max-w-md mx-auto px-4 py-8 sm:py-12">
        <div class="mb-4">
            <a href="{{ path('app_profile') }}" class="text-sm text-primary-light hover:text-primary no-underline">&larr; {{ 'profile.edit.back'|trans }}</a>
        </div>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sm:p-8">
            <h1 class="text-2xl font-bold text-gray-900 mb-6">{{ 'profile.change_password.title'|trans }}</h1>

            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                <div class="mb-4">
                    {{ form_label(form.currentPassword, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.currentPassword, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.currentPassword) }}
                </div>

                <div class="mb-4">
                    {{ form_label(form.newPassword.first, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.newPassword.first, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.newPassword.first) }}
                </div>

                <div class="mb-6">
                    {{ form_label(form.newPassword.second, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.newPassword.second, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.newPassword) }}
                </div>

                <button type="submit" class="w-full py-3 bg-primary-light text-white font-semibold rounded-lg hover:bg-primary transition">
                    {{ 'profile.change_password.submit'|trans }}
                </button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'profile.edit.title'|trans }}{% endblock %}

{% block body %}
    <div class="max-w-md mx-auto px-4 py-8 sm:py-12">
        <div class="mb-4">
            <a href="{{ path('app_profile') }}" class="text-sm text-primary-light hover:text-primary no-underline">&larr; {{ 'profile.edit.back'|trans }}</a>
        </div>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sm:p-8">
            <h1 class="text-2xl font-bold text-gray-900 mb-6">{{ 'profile.edit.title'|trans }}</h1>

            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                <div class="mb-4">
                    {{ form_label(form.firstName, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.firstName, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.firstName) }}
                </div>

                <div class="mb-4">
                    {{ form_label(form.lastName, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.lastName, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.lastName) }}
                </div>

                <div class="mb-6">
                    {{ form_label(form.phone, null, {'label_attr': {'class': 'block text-sm font-medium text-gray-700 mb-1'}}) }}
                    {{ form_widget(form.phone, {'attr': {'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent'}}) }}
                    {{ form_errors(form.phone) }}
                </div>

                <button type="submit" class="w-full py-3 bg-primary-light text-white font-semibold rounded-lg hover:bg-primary transition">
                    {{ 'profile.edit.submit'|trans }}
                </button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'profile.title'|trans }}{% endblock %}

{% block body %}
    <div class="max-w-lg mx-auto px-4 py-8 sm:py-12">
        <h1 class="text-2xl font-bold text-gray-900 mb-6">{{ 'profile.title'|trans }}</h1>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sm:p-8">
            <dl class="space-y-4">
                <div class="flex justify-between text-sm">
                    <dt class="text-gray-500">{{ 'profile.show.email'|trans }}</dt>
                    <dd class="text-gray-800 font-medium">{{ user.email }}</dd>
                </div>
                <div class="flex justify-between text-sm border-t border-gray-100 pt-4">
                    <dt class="text-gray-500">{{ 'profile.show.first_name'|trans }}</dt>
                    <dd class="text-gray-800">{{ user.firstName ?? '—' }}</dd>
                </div>
                <div class="flex justify-between text-sm border-t border-gray-100 pt-4">
                    <dt class="text-gray-500">{{ 'profile.show.last_name'|trans }}</dt>
                    <dd class="text-gray-800">{{ user.lastName ?? '—' }}</dd>
                </div>
                <div class="flex justify-between text-sm border-t border-gray-100 pt-4">
                    <dt class="text-gray-500">{{ 'profile.show.phone'|trans }}</dt>
                    <dd class="text-gray-800">{{ user.phone ?? '—' }}</dd>
                </div>
                <div class="flex justify-between text-sm border-t border-gray-100 pt-4">
                    <dt class="text-gray-500">{{ 'profile.show.verified'|trans }}</dt>
                    <dd>
                        {% if user.verified %}
                            <span class="inline-block px-2 py-0.5 text-xs font-medium rounded-full bg-green-100 text-green-800">{{ 'profile.show.yes'|trans }}</span>
                        {% else %}
                            <span class="inline-block px-2 py-0.5 text-xs font-medium rounded-full bg-red-100 text-red-800">{{ 'profile.show.no'|trans }}</span>
                        {% endif %}
                    </dd>
                </div>
            </dl>

            <div class="flex flex-col sm:flex-row gap-3 mt-8 pt-6 border-t border-gray-200">
                <a href="{{ path('app_profile_edit') }}" class="px-4 py-2 bg-primary-light text-white rounded-lg font-medium hover:bg-primary transition-colors no-underline text-sm text-center">
                    {{ 'profile.show.edit_button'|trans }}
                </a>
                <a href="{{ path('app_profile_change_password') }}" class="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-colors no-underline text-sm text-center">
                    {{ 'profile.show.change_password_button'|trans }}
                </a>
            </div>
        </div>
    </div>
{% endblock %}